security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: backoffice_login
                check_path: backoffice_login
                default_target_path: app_frontoffice
            logout:
                path: backoffice_logout
                target: app_frontoffice

    access_control:
        - { path: ^/backoffice, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            App\Entity\User: 'auto'
            App\Entity\Admin: 'auto'
            App\Entity\Etudiant: 'auto'

        # NE PAS RÉPÉTER access_control ici !
        # La configuration access_control est héritée de la section principale