vich_uploader:
    db_driver: orm

    mappings:
        post_images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        post_videos:
            uri_prefix: /uploads/videos
            upload_destination: '%kernel.project_dir%/public/uploads/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer